# Dependabot configuration for automated dependency updates
# This configuration enables weekly dependency updates for Composer, npm, and GitHub Actions
# Updates are grouped by ecosystem to reduce noise and make reviews more manageable

version: 2
updates:
  # Composer package updates for PHP dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    groups:
      # Group all Composer updates together to reduce PR noise
      composer-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "malunem"
    labels:
      - "dependencies"
      - "composer"
      - "php"
    commit-message:
      prefix: "composer"
      include: "scope"

  # npm package updates for JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    groups:
      # Group all npm updates together to reduce PR noise
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "malunem"
    labels:
      - "dependencies"
      - "npm"
      - "javascript"
    commit-message:
      prefix: "npm"
      include: "scope"

  # GitHub Actions updates (if any workflow files exist)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    groups:
      # Group all GitHub Actions updates together
      github-actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "malunem"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    commit-message:
      prefix: "github-actions"
      include: "scope"